replicaCount: 2

image:
  repository: ghcr.io/ldest/sre-course/api
  pullPolicy: IfNotPresent
  tag: "f0135e1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

autoscaling: {}

serviceAccount: {}

service:
  type: ClusterIP
  port: 8080

variables:
  ASPNETCORE_URLS: http://*:8080
  CONNECTIONSTRINGS__PGCONNECTION: server=XXX; port=5000; database=weather; user id=weather_role; password=XXX;

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: api.sre-course.vagachev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
